package com.rnsecurity.detectors.hardware

import android.content.pm.PackageManager
import com.rnsecurity.engine.CheckEngine
import com.rnsecurity.engine.CheckOptions
import com.rnsecurity.engine.Confidence
import com.rnsecurity.engine.Detector
import com.rnsecurity.engine.SecuritySignal
import com.rnsecurity.engine.SignalOutcome
import com.rnsecurity.probe.ProbeSet

/**
 * Secure hardware capability reporting for Android.
 *
 * This check is a different shape from root, hook or integrity detection. There
 * is no adversary here — nothing is hiding from us — so "detected" cannot mean
 * "an attack was found". It means **a weakness indicator fired**: the platform
 * offers less protection than an application handling sensitive material would
 * want.
 *
 * The reverse framing matters just as much. A device having a hardware-backed
 * keystore says **nothing** about whether this application uses it correctly, or
 * at all. `secure` here means "the hardware is available", never "your data is
 * safe" — the brief is explicit that the presence of a Keystore must not be
 * allowed to imply a secure application architecture.
 *
 * See `docs/runtime/secure-hardware.md`.
 */

private fun indeterminate(id: String, confidence: Confidence, why: String) =
  SecuritySignal(
    id = id,
    outcome = SignalOutcome.INDETERMINATE,
    confidence = confidence,
    description = "Hardware capability could not be determined: $why"
  )

private fun outcomeOf(weaknessPresent: Boolean) =
  if (weaknessPresent) SignalOutcome.DETECTED else SignalOutcome.NOT_DETECTED

/**
 * Keys generated by this application are not backed by secure hardware.
 *
 * Established by generating a throwaway key and inspecting it, then deleting it.
 * Capability flags describe what a device *has*; only an actual key tells you
 * what your keys will get.
 */
internal class KeyStorageBackingDetector : Detector {
  override val id = "RNSEC-RUNTIME-HARDWARE-001"

  override fun detect(probes: ProbeSet): SecuritySignal {
    val level =
      probes.keystore.keySecurityLevel()
        ?: return indeterminate(id, Confidence.HIGH, "a probe key could not be generated")

    val softwareBacked = level == "software"
    val unknownBacking = level == "unknown"

    if (unknownBacking) {
      return indeterminate(id, Confidence.HIGH, "the platform did not report a security level")
    }

    return SecuritySignal(
      id = id,
      outcome = outcomeOf(softwareBacked),
      confidence = Confidence.HIGH,
      description =
        if (softwareBacked) {
          "Keys generated by this application are backed by software, not secure hardware"
        } else {
          "Keys generated by this application are backed by secure hardware"
        },
      metadata = mapOf("securityLevel" to level)
    )
  }
}

/**
 * StrongBox is not available.
 *
 * A dedicated secure element rather than a TEE. Its absence is entirely normal —
 * most Android devices do not have one — so this is `low` confidence and is only
 * worth acting on for applications that specifically require that tier.
 */
internal class StrongBoxDetector : Detector {
  override val id = "RNSEC-RUNTIME-HARDWARE-002"

  override fun detect(probes: ProbeSet): SecuritySignal {
    val available =
      probes.device.hasSystemFeature(FEATURE_STRONGBOX)
        ?: return indeterminate(id, Confidence.LOW, "the platform feature list was unavailable")

    return SecuritySignal(
      id = id,
      outcome = outcomeOf(!available),
      confidence = Confidence.LOW,
      description =
        if (!available) {
          "StrongBox-backed key storage is not available on this device"
        } else {
          "StrongBox-backed key storage is available on this device"
        },
      metadata = mapOf("strongBoxAvailable" to available)
    )
  }

  private companion object {
    const val FEATURE_STRONGBOX = PackageManager.FEATURE_STRONGBOX_KEYSTORE
  }
}

/**
 * Hardware-backed key attestation is not available.
 *
 * Attestation is what lets a *server* verify a key really lives in secure
 * hardware. Without it, everything this check reports is a claim the device
 * makes about itself — which is exactly the kind of claim a compromised device
 * is free to fabricate.
 */
internal class KeyAttestationDetector : Detector {
  override val id = "RNSEC-RUNTIME-HARDWARE-003"

  override val minSdk = 31

  override fun detect(probes: ProbeSet): SecuritySignal {
    val available =
      probes.device.hasSystemFeature(FEATURE_HARDWARE_KEYSTORE)
        ?: return indeterminate(id, Confidence.MEDIUM, "the platform feature list was unavailable")

    return SecuritySignal(
      id = id,
      outcome = outcomeOf(!available),
      confidence = Confidence.MEDIUM,
      description =
        if (!available) {
          "Hardware-backed key attestation is not available on this device"
        } else {
          "Hardware-backed key attestation is available on this device"
        },
      metadata = mapOf("keyAttestationAvailable" to available)
    )
  }

  private companion object {
    const val FEATURE_HARDWARE_KEYSTORE = "android.hardware.hardware_keystore"
  }
}

/** The secure hardware check. */
internal class SecureHardwareCheckEngine : CheckEngine {
  override val checkId = "secureHardware"

  override fun detectors(options: CheckOptions): List<Detector> =
    listOf(KeyStorageBackingDetector(), StrongBoxDetector(), KeyAttestationDetector())

  override fun metadata(probes: ProbeSet, options: CheckOptions): Map<String, Any?> =
    mapOf(
      // Stated in the result itself so it cannot be missed by someone reading a
      // report rather than the documentation.
      "note" to
        "Hardware availability describes the device, not this application's use of it."
    )
}
