import Foundation
import UIKit

/// Swift-side entry point for the iOS security engine.
///
/// The TurboModule specification generated by Codegen is a C++/Objective-C
/// protocol that Swift cannot conform to directly, so `SecurityToolkit.mm` owns
/// the protocol conformance and forwards here. Detection logic lives in
/// `ios/Engine`, which is Foundation-only and unit-tested with `swift test`.
@objc(RNSecurityToolkitEngine)
public final class SecurityToolkitEngine: NSObject {

  /// Built once. `ProbeSet` construction touches `UIApplication`, so it is
  /// captured on the main thread and then used freely from the engine queue.
  private static let engine: IOSSecurityEngine = {
    let probes =
      Thread.isMainThread
      ? MainActor.assumeIsolated { IOSProbeSetFactory.create() }
      : DispatchQueue.main.sync { MainActor.assumeIsolated { IOSProbeSetFactory.create() } }
    return IOSSecurityEngine(probes: probes)
  }()

  /// Returns identifying information about the native engine.
  ///
  /// - Parameter engineVersion: supplied by the Objective-C++ layer, which reads
  ///   it from a header generated from `package.json`.
  @objc
  public static func engineInfo(engineVersion: String) -> [String: Any] {
    [
      "platform": "ios",
      "osVersion": UIDevice.current.systemVersion,
      "engineVersion": engineVersion,
      "supportedChecks": engine.supportedChecks(),
    ]
  }

  /// Runs one check.
  ///
  /// A check this platform does not implement resolves as `unavailable` with
  /// `platform-not-supported` — a platform fact, not a failure.
  @objc
  public static func runCheck(_ checkId: String, options: [String: Any]) -> [String: Any] {
    engine.run(checkId, options: CheckOptions(options)).toPayload()
  }

  /// Runs several checks in one bridge crossing.
  @objc
  public static func runChecks(_ checkIds: [String], options: [String: Any]) -> [String: Any] {
    ["results": engine.runAll(checkIds, options: CheckOptions(options)).map { $0.toPayload() }]
  }

  /// Applies or removes screen capture protection.
  ///
  /// iOS has no public API to prevent a screenshot, so there is nothing honest to
  /// do here yet. Returning `false` says the request did not take effect rather
  /// than pretending it did. See `docs/runtime/screen-security.md`.
  @objc
  public static func setScreenProtection(_ enabled: Bool) -> Bool {
    false
  }
}
