import { createCheck } from './createCheck';
import type { SecurityCheckResult } from '../types';

/**
 * Secure hardware capability.
 *
 * Reports what key protection this device can actually give you: whether keys
 * generated by this application are backed by secure hardware, whether StrongBox
 * is present, and whether hardware-backed key attestation is available.
 *
 * @remarks
 * This is a **capability report, not a threat detection**. A `detected` status
 * here means a weakness indicator fired — the platform offers less than an
 * application handling sensitive material would want — rather than that an
 * attack was found.
 *
 * The reverse matters just as much: a device having a hardware-backed keystore
 * says nothing about whether this application uses it, or uses it correctly.
 * `secure` means the hardware is available. It does not mean your data is safe.
 *
 * @see docs/runtime/secure-hardware.md
 */
export const SecureHardware: {
  getStatus(): Promise<SecurityCheckResult>;
} = {
  getStatus: createCheck('secureHardware'),
};
